{
  "code": "INTERNAL_ERROR",
  "details": "[Errno 2] No such file or directory: '/Users/yan/Documents/GitHub/Python/ProjetoAuditoria/app/data/exports/documentacao_seo_87c85de7-d6ba-4593-9a0a-5c81aa47c326_20250927_214114.docx'",
  "error": "Erro interno do servidor"
}
